### ISSUE TITLE
Bug with teleporting

### ISSUE THREAD

**Issue by LoneWolfHT** [octacian/savepos#1]
Example:
I have 3 homes:
**Test1 (123 4 567)
Test2 (891 2 345)
Test3 (678 9 123)**
Whenever I click on Test3 I teleport to Test1. When I click on Test2 I teleport to Test2. When I try to delete Test1 I get a message saying: "Are you sure you want to delete Test1?"
Great CSM btw. It's VERY useful on HOMETOWN  :+1:

**Comment by LoneWolfHT** [comment]
This seems to happen whenever you set your 10th pos

**Comment by octacian** [comment]
Thanks for reporting this issue! This bug has been fixed in the commit referenced below. And yeah, I did see the typo, but not until it was too late. There have already been so many commits since then that there is nothing I can do about it :smile:

20c0c5c4253a4f9146979e6c509d7f8bd0207b0a
